Migration API Payment & Address
Ecowave-Alterra/ecowave-flutter pull request #68
Opened 2023-06-23 12:57 UTC by fauzan2720

- menyelesaikan migrasi api

[FL-031 - Address](https://trello.com/c/L4oAt9NO)
[FL-035 - Detail Pembayaran](https://trello.com/c/XPh8ezbh)
[FL-036 - Pilih Alamat Pengiriman](https://trello.com/c/R7hFGJoT)
[FL-037 - Pilih Opsi Pengiriman](https://trello.com/c/fozZZ4jb)
[FL-038 - Voucher](https://trello.com/c/T40972cK)
[FL-040 - Pembayaran](https://trello.com/c/NsEmjdK4)

2023-06-23 14:44 UTC, WahyuOzora1 approved these changes

2023-06-23 14:48 UTC, Kev9794 requested changes
di Card product yang Detail: itu kayanya Kategori :

2023-06-23 16:14 UTC, FauziMaulia approved these changes

2023-06-23 16:22 UTC, Kev9794 approved these changes

2023-06-23 16:22 UTC, Kev9794 approved these changes

2023-06-24 03:14 UTC, dafisatria approved these changes

2023-06-24 03:18 UTC, merged