Fix bug/fl 028
Ecowave-Alterra/ecowave-flutter pull request #76
Opened 2023-06-26 16:34 UTC by dafisatria

https://github.com/Ecowave-Alterra/ecowave-flutter/assets/96201555/b76c6404-6fac-4feb-9013-01b35f1e3c47

2023-06-26 16:56 UTC, fauzan2720 requested changes
finite scroll

2023-06-26 16:56 UTC, fauzan2720 commented on lib/features/home/view/dashboard_page.dart
> +    context.read<InformationBloc>().add(GetInformationEvent(id: 1));
Reminder:
1. ```git pull origin main```
2. bersihkan problems di console

2023-06-26 16:56 UTC, fauzan2720 commented on lib/features/information/bloc/information/information_bloc.dart
1. buat event baru untuk get more info
```shell
class GetMoreInformationEvent extends InformationEvent {
  final int id;
  const GetMoreInformationEvent({
    required this.id,
  });
}
```

2. atur state nya dengan equatable, agar state data dicek apakah ada pembaruan data atau tidak
```shell
class InformationSuccess extends InformationState {
  final List<InformationModel> data;

  const InformationSuccess({
    required this.data,
  });

  @override
  List<Object> get props => [data];
}
```

3. buat fungsi baru di bloc untuk event GetMoreInformation
```shell
    on<GetMoreInformationEvent>((event, emit) async {
      try {
        final List<InformationModel> result =
            await service.getInformation(id: event.id);

        final InformationSuccess currentState = state as InformationSuccess;
        emit(InformationSuccess(data: [...currentState.data, ...result]));
      } catch (e) {
        emit(InformationError(message: e.toString()));
      }
    });
```

4. ubah fungsi ketika scroll menjadi
```shell
context.read<InformationBloc>().add(GetMoreInformationEvent(id: page + 1));
```

2023-06-26 17:20 UTC, dafisatria commented on lib/features/information/bloc/information/information_bloc.dart
https://github.com/Ecowave-Alterra/ecowave-flutter/assets/96201555/c2e0ab02-5563-4795-9807-57833305f763

biar limit gimana zan?

2023-06-26 17:25 UTC, fauzan2720 commented on lib/features/information/bloc/information/information_bloc.dart
Ngatur limit biasanya kalau disediakan sama BE

2023-06-26 17:29 UTC, dafisatria commented on lib/features/information/bloc/information/information_bloc.dart
berarti ini dibiarin gini dulu aja kah?

2023-06-26 17:32 UTC, fauzan2720 commented on lib/features/information/bloc/information/information_bloc.dart
Iyapp gitu udah bener menurutku

2023-06-26 17:32 UTC, dafisatria commented on lib/features/information/bloc/information/information_bloc.dart
mantap

2023-06-26 17:46 UTC, fauzan2720 approved these changes

2023-06-27 02:41 UTC, FauziMaulia approved these changes

2023-06-27 03:00 UTC, WahyuOzora1 approved these changes

2023-06-27 04:09 UTC, Kev9794 approved these changes

2023-06-27 04:09 UTC, merged