Fixing bug/random
Ecowave-Alterra/ecowave-flutter pull request #82
Opened 2023-07-23 08:07 UTC by WahyuOzora1

2023-07-25 07:39 UTC, fauzan2720 requested changes
scroll

2023-07-25 07:39 UTC, fauzan2720 commented on lib/features/home/view/dashboard_page.dart
> +        child: Column(
menurutku lebih baik SingleChildScrollView ditaruh sebagai parrent dari Column, biar backgroundnya bisa ke scroll juga.
atau Column diganti ListView (SingleChildScrollView dihapus)

2023-07-25 11:27 UTC, WahyuOzora1 commented on lib/features/home/view/dashboard_page.dart
> +        child: Column(
Ohh ya ga ku perhatikan asal ngikut kode sebelumnya, okei ntar ku ganti

2023-07-29 01:29 UTC, fauzan2720 commented on lib/features/home/view/dashboard_page.dart
> +                        child: SingleChildScrollView(
Di ListView udah scroll, disini ada scroll lagi, apa ada alasan?

2023-07-29 01:49 UTC, WahyuOzora1 commented on lib/features/home/view/dashboard_page.dart
> +                        child: SingleChildScrollView(
Gaada sih zan, keknya kemarin buru" lupa hapus dan asal jadi :v, udah aku perbaiki

2023-07-29 01:53 UTC, fauzan2720 approved these changes

2023-07-29 01:54 UTC, merged